version: '3.9'

services:
  mysql-db:
    container_name: mysql-smartfox-dev
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ./mysqlDB:/var/lib/mysql
    restart: always

  phpmyadmin-db:
    image: phpmyadmin/phpmyadmin
    container_name: pma-smartfox-dev
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
    ports:
      - "8080:80"
    restart: always
