version: '3.9'

services:
  client:
    container_name: client-smartfox-dev
    build: ./client
    ports:
      - "80:80"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always 

  server:
    container_name: server-smartfox-dev
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EXPRESS_PORT=${EXPRESS_PORT}
    restart: always  

  mysql-db:
    container_name: mysql-smartfox-dev
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_DATABASE=foxdrive
    volumes:
      - ./mysqlDB:/var/lib/mysql
    restart: always

  phpmyadmin-db:
    image: phpmyadmin/phpmyadmin
    container_name: pma-smartfox-dev
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
    ports:
      - "8080:80"
    restart: always
