version: '3.9'

services:
  client:
    container_name: client-smartfox-prod
    build: ./client
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: always 

  server:
    container_name: server-smartfox-prod
    build: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - EXPRESS_PORT=${EXPRESS_PORT}
    restart: always  

  mysql-db:
    container_name: mysql-smartfox-prod
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    restart: always

  phpmyadmin-db:
    image: phpmyadmin/phpmyadmin
    container_name: pma-smartfox-prod
    depends_on:
      - mysql-db
    environment:
      - PMA_HOST=mysql-db
    ports:
      - "5050:80"
    restart: always
